include:
    - openstack.glance.api
    - openstack.glance.registry
    - openstack.nova.api
    - openstack.nova.conductor
    - openstack.nova.scheduler
    - openstack.cinder.api
    - openstack.cinder.scheduler
    - openstack.quantum.api
    - openstack.keystone.api
    - openstack.horizon.dashboard
